# Generated by Django 3.1.7 on 2021-04-10 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='upload',
            field=models.FileField(blank=True, upload_to='uploads/'),
        ),
    ]
