# Generated by Django 3.1.7 on 2021-04-10 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0002_auto_20210410_1709'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='branch',
            new_name='branch1',
        ),
        migrations.AddField(
            model_name='project',
            name='branch2',
            field=models.CharField(choices=[('ECE', 'ECE'), ('EEE', 'EEE'), ('CSE', 'CSE'), ('IT', 'IT'), ('MEC', 'MEC')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='branch3',
            field=models.CharField(choices=[('ECE', 'ECE'), ('EEE', 'EEE'), ('CSE', 'CSE'), ('IT', 'IT'), ('MEC', 'MEC')], max_length=200, null=True),
        ),
    ]
