# Generated by Django 3.1.7 on 2021-04-10 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0003_auto_20210410_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='branch2',
            field=models.CharField(blank=True, choices=[('ECE', 'ECE'), ('EEE', 'EEE'), ('CSE', 'CSE'), ('IT', 'IT'), ('MEC', 'MEC')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='branch3',
            field=models.CharField(blank=True, choices=[('ECE', 'ECE'), ('EEE', 'EEE'), ('CSE', 'CSE'), ('IT', 'IT'), ('MEC', 'MEC')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='platform2',
            field=models.CharField(blank=True, choices=[('EMBEDDED SYSTEM', 'EMBEDDED SYSTEM'), ('VLSI', 'VLSI'), ('IOT', 'IOT'), ('WEB TECHNOLOGY', 'WEB TECHNOLOGY'), ('IMAGE PROCESSING', 'IMAGE PROCESSING'), ('ROBOTICS', 'ROBOTICS'), ('POWER ELECTRONICS', 'POWER ELECTRONIC'), ('DATA SCIENCE', 'DATA SCIENCE'), ('CLOUD COMPUTING', 'CLOUD COMPUTING'), ('ELECTRONICS', 'ELECTRONICS'), ('COMMUNICATION', 'COMMUNICATION'), ('COMPUTER VISION', 'COMPUTER VISION'), ('DEEP LEARNING', 'DEEP LEARNING')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='platform3',
            field=models.CharField(blank=True, choices=[('EMBEDDED SYSTEM', 'EMBEDDED SYSTEM'), ('VLSI', 'VLSI'), ('IOT', 'IOT'), ('WEB TECHNOLOGY', 'WEB TECHNOLOGY'), ('IMAGE PROCESSING', 'IMAGE PROCESSING'), ('ROBOTICS', 'ROBOTICS'), ('POWER ELECTRONICS', 'POWER ELECTRONIC'), ('DATA SCIENCE', 'DATA SCIENCE'), ('CLOUD COMPUTING', 'CLOUD COMPUTING'), ('ELECTRONICS', 'ELECTRONICS'), ('COMMUNICATION', 'COMMUNICATION'), ('COMPUTER VISION', 'COMPUTER VISION'), ('DEEP LEARNING', 'DEEP LEARNING')], max_length=200, null=True),
        ),
    ]
